---
    os: linux
    language: node_js
    node_js:
        - 'node'
        - '10'

    notifications:
        webhooks:
            urls:
                - https://discordhooks.herokuapp.com/travis
            on_success: always
            on_failure: always
            on_start: always
            on_cancel: always
            on_error: always
